name: betrade
description: "BeTrade Project"
publish_to: 'none'
version: 1.0.0+11

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.0
  shared_preferences: ^2.2.2
  iconsax: ^0.0.8
  http: ^1.2.0
  provider: ^6.1.5+1
  flutter_dotenv: ^6.0.0
  fl_chart: ^1.2.0
  permission_handler: ^12.0.1
  camera: ^0.12.0+1
  dio: ^5.4.0
  image_picker: ^1.0.7
  path_provider: ^2.1.5
  http_parser: ^4.1.2
  flutter_image_compress: ^2.4.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/logo/
    - .env

  fonts:
    - family: SFProRounded
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded-Regular.ttf
          weight: 400

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/app_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo/app_icon.png"