// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8sL6aKDZi03BiM9Cq_m80FLqxUW4mbf0',
    appId: '1:795194194311:web:e55841acd9c06c60a73b22',
    messagingSenderId: '795194194311',
    projectId: 'betrade-4efd1',
    authDomain: 'betrade-4efd1.firebaseapp.com',
    storageBucket: 'betrade-4efd1.firebasestorage.app',
    measurementId: 'G-R004L16DC8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6IPTdXK_Rbzv571JuRc_r2nMC1HyicXM',
    appId: '1:577626610829:android:ce408e8d2bf8b6a79dd6c4',
    messagingSenderId: '577626610829',
    projectId: 'betrade-new',
    storageBucket: 'betrade-new.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNClXQ4whn4HdYcBWmEWYzuWXzVvMEF20',
    appId: '1:577626610829:ios:ad98598875b8e3839dd6c4',
    messagingSenderId: '577626610829',
    projectId: 'betrade-new',
    storageBucket: 'betrade-new.firebasestorage.app',
    iosBundleId: 'com.build.betrade',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkB_Y3Oq-xxxbLnpri1KCr63-GUszfpEQ',
    appId: '1:795194194311:ios:8f7cf0e14c9b197fa73b22',
    messagingSenderId: '795194194311',
    projectId: 'betrade-4efd1',
    storageBucket: 'betrade-4efd1.firebasestorage.app',
    iosBundleId: 'com.build.betrade',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8sL6aKDZi03BiM9Cq_m80FLqxUW4mbf0',
    appId: '1:795194194311:web:50e18c1699035ba8a73b22',
    messagingSenderId: '795194194311',
    projectId: 'betrade-4efd1',
    authDomain: 'betrade-4efd1.firebaseapp.com',
    storageBucket: 'betrade-4efd1.firebasestorage.app',
    measurementId: 'G-X731VNTFTR',
  );
}